feature/menu
chidorishar/icecream-team-project pull request #12
Opened 2022-06-24 21:54 UTC by IrynaKniazieva

добавлена разметка html, стили scss, не работает js

2022-06-25 12:32 UTC, chidorishar requested changes
доработать

2022-06-26 13:33 UTC, IrynaKniazieva commented on src/sass/layout/_header-hero.scss
> +    border-bottom: 1px solid #E18298;
готово

2022-06-26 13:33 UTC, IrynaKniazieva commented on src/sass/layout/_header-hero.scss
> +    background-color: #E17992;
готово

2022-06-26 13:33 UTC, IrynaKniazieva commented on src/sass/layout/_header-hero.scss
> +    background-color: rgba(0,0,0,0.3);
готово

2022-06-26 13:41 UTC, IrynaKniazieva commented on src/sass/layout/_header-hero.scss
> +    fill: #D41443;
кнопок стало две, они разных цветов, один ховер и фокус им не подойдет. 
    Для бургера применила getColorFromPalette('hovered', 'additional');   
    Для крестика getColorFromPalette('hovered', 'main');

2022-06-28 21:48 UTC, chidorishar approved these changes

2022-06-28 21:49 UTC, merged